# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_can', models.CharField(max_length=20, null=True, verbose_name='实际能审批/执行的用户或组')),
                ('approver', models.CharField(max_length=20, verbose_name='审批/执行人')),
                ('result', models.CharField(choices=[('0', '同意执行'), ('1', '拒绝执行'), ('2', '暂缓执行'), ('3', '执行异常')], max_length=10, verbose_name='审批/执行结果')),
                ('approval_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '审批表',
                'db_table': 'approval_form',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=50, unique=True, verbose_name='流程步骤')),
                ('setp_id', models.PositiveSmallIntegerField(unique=True, verbose_name='步骤id')),
                ('applicant_require', models.CharField(choices=[('1', '用户所属组'), ('2', 'QA组'), ('3', 'OPS组'), ('4', '用户自己'), ('5', '指定具体某个用户'), ('6', '终级大boss')], max_length=10, verbose_name='有审核权限的用户或组')),
            ],
            options={
                'verbose_name': '工单流程表',
                'db_table': 'process',
                'ordering': ['setp_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='工单标题')),
                ('level', models.CharField(choices=[('0', '重要且紧急'), ('1', '重要但不紧急'), ('2', '不重要但紧急'), ('3', '不重要且不紧急')], max_length=50, verbose_name='紧急程度')),
                ('detail', models.CharField(max_length=800, null=True, verbose_name='详情')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '完成'), ('2', '暂停'), ('3', '取消')], default='0', max_length=10, verbose_name='工单状态')),
                ('applicant', models.CharField(max_length=50, null=True, verbose_name='申请人')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单创建时间')),
                ('complete_time', models.DateTimeField(null=True, verbose_name='工单完成时间')),
                ('module_name', models.CharField(max_length=500, null=True, verbose_name='模块名称')),
                ('sql', models.CharField(choices=[('yes', '有'), ('no', '无')], default='no', max_length=10, verbose_name='是否存在SQL')),
                ('sql_detail', models.CharField(max_length=1000, null=True, verbose_name='SQL语句')),
                ('sql_file_url', models.CharField(max_length=1000, null=True, verbose_name='SQL附件的URL')),
                ('process', models.ManyToManyField(null=True, to='workform.ProcessModel', verbose_name='与发布流程步骤多对多关联')),
            ],
            options={
                'verbose_name': '工单列表',
                'db_table': 'workform',
            },
        ),
        migrations.CreateModel(
            name='WorkFormTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工单类型名称')),
                ('cn_name', models.CharField(max_length=200, verbose_name='工单类型中文名称')),
                ('process_id', models.CharField(max_length=500, null=True, verbose_name='需要执行的工单流程')),
            ],
            options={
                'verbose_name': '工单类型表',
                'db_table': 'workform_type',
            },
        ),
        migrations.AddField(
            model_name='workformmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workform.WorkFormTypeModel', verbose_name='工单类型,与工单类型表多对一关联'),
        ),
        migrations.AddField(
            model_name='approvalformmodel',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workform.ProcessModel', verbose_name='与发布流程步骤多对一关联'),
        ),
        migrations.AddField(
            model_name='approvalformmodel',
            name='workform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workform.WorkFormModel', verbose_name='关联发布工单记录'),
        ),
    ]
