# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0002_auto_20180119_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workformtypemodel',
            old_name='process_id',
            new_name='process_step_id',
        ),
    ]
