# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0003_auto_20180119_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalformmodel',
            name='approve_note',
            field=models.CharField(max_length=1000, null=True, verbose_name='审批/执行备注'),
        ),
        migrations.AlterField(
            model_name='approvalformmodel',
            name='approver',
            field=models.CharField(max_length=20, null=True, verbose_name='审批/执行人'),
        ),
        migrations.AlterField(
            model_name='approvalformmodel',
            name='result',
            field=models.CharField(choices=[('0', '同意执行'), ('1', '拒绝执行'), ('2', '暂缓执行'), ('3', '执行异常')], max_length=10, null=True, verbose_name='审批/执行结果'),
        ),
    ]
