# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workform', '0004_auto_20180120_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmodel',
            name='applicant_require_type',
            field=models.CharField(choices=[('0', '组审核'), ('1', '单用户审核')], default='0', max_length=10, verbose_name='标记有审核权限的是单用户还是组'),
        ),
        migrations.AlterField(
            model_name='approvalformmodel',
            name='approver',
            field=models.CharField(max_length=20, null=True, verbose_name='最终审批/执行人'),
        ),
        migrations.RemoveField(
            model_name='approvalformmodel',
            name='approver_can',
        ),
        migrations.AddField(
            model_name='approvalformmodel',
            name='approver_can',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='实际能审批/执行的用户集合'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='applicant_require',
            field=models.CharField(choices=[('0', '终级大boss'), ('1', '用户所属组leader'), ('2', 'QA组'), ('3', 'OPS组'), ('4', '用户自己'), ('5', '指定具体某个用户'), ('6', '雪良组'), ('7', '君禄组'), ('8', '华俊组')], max_length=10, verbose_name='有审核权限的用户或组'),
        ),
    ]
