# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0005_auto_20180120_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmodel',
            name='applicant_require_type',
        ),
    ]
