# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0007_auto_20180121_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workformmodel',
            name='process',
        ),
        migrations.AddField(
            model_name='workformmodel',
            name='process_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workform.ProcessModel', verbose_name='与流程步骤多对一关联'),
        ),
        migrations.AlterField(
            model_name='workformmodel',
            name='status',
            field=models.CharField(choices=[('0', '申请中'), ('1', '完成'), ('2', '暂停'), ('3', '取消')], default='0', max_length=10, verbose_name='工单状态'),
        ),
    ]
