# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0008_auto_20180121_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workformmodel',
            name='level',
            field=models.CharField(choices=[('0', '重要且紧急'), ('1', '不重要但紧急'), ('2', '重要但不紧急'), ('3', '不重要且不紧急')], max_length=50, verbose_name='紧急程度'),
        ),
    ]
