# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workform', '0009_auto_20180121_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workformmodel',
            options={'ordering': ['-id'], 'verbose_name': '工单列表'},
        ),
        migrations.AddField(
            model_name='workformmodel',
            name='approver_can',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='与User表建立多对多关联,声明该流程步骤能审批/执行的用户集合,具体的用户集合从ApprovalFormModel的approver_can字段同步'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='applicant_require',
            field=models.CharField(choices=[('0', '终级大boss'), ('1', '用户所属组leader'), ('2', 'QA组'), ('3', 'OPS组'), ('4', '用户自己'), ('5', '指定具体某个用户'), ('6', '雪良组'), ('7', '君禄组'), ('8', '华俊组')], max_length=10, verbose_name='期待有审核权限的用户或组,只是一个标记,具体逻辑后端定义'),
        ),
    ]
