# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0011_auto_20180123_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workformmodel',
            name='status',
            field=models.CharField(choices=[('0', '待审批'), ('1', '已完成'), ('2', '暂停'), ('3', '取消')], default='0', max_length=10, verbose_name='工单状态'),
        ),
    ]
