# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workform', '0015_auto_20180123_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processmodel',
            old_name='applicant_require',
            new_name='approval_require',
        ),
        migrations.RemoveField(
            model_name='approvalformmodel',
            name='approver_can',
        ),
        migrations.RemoveField(
            model_name='workformmodel',
            name='approver_can',
        ),
        migrations.AddField(
            model_name='approvalformmodel',
            name='approval_can',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='实际能审批/执行的用户集合'),
        ),
        migrations.AddField(
            model_name='workformmodel',
            name='approval_can',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='与User表建立多对多关联,声明该流程步骤能审批/执行的用户集合,具体的用户集合从ApprovalFormModel的approver_can字段同步'),
        ),
    ]
