# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0016_auto_20180123_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalformmodel',
            old_name='approval_can',
            new_name='approver_can',
        ),
        migrations.RenameField(
            model_name='workformmodel',
            old_name='approval_can',
            new_name='approver_can',
        ),
    ]
