# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0017_auto_20180123_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmodel',
            name='approval_require',
            field=models.CharField(choices=[('0', '终级大boss'), ('1', '用户所属组leader'), ('2', 'QA组'), ('3', 'OPS组'), ('4', '用户自己'), ('5', '指定具体某个用户'), ('6', '雪良组'), ('7', '君禄组'), ('8', '华俊组'), ('9', '无')], max_length=10, verbose_name='期待有审核权限的用户或组,只是一个标记,具体逻辑后端定义'),
        ),
    ]
