# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0018_auto_20180123_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalformmodel',
            name='approver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最终审批/执行人'),
        ),
        migrations.AlterField(
            model_name='approvalformmodel',
            name='approver_can',
            field=models.ManyToManyField(null=True, related_name='_approvalformmodel_approver_can_+', to=settings.AUTH_USER_MODEL, verbose_name='实际能审批/执行的用户集合'),
        ),
        migrations.AlterField(
            model_name='workformmodel',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='申请人,与用户表一对一关联'),
        ),
        migrations.AlterField(
            model_name='workformmodel',
            name='approver_can',
            field=models.ManyToManyField(related_name='_workformmodel_approver_can_+', to=settings.AUTH_USER_MODEL, verbose_name='与User表建立多对多关联,声明该流程步骤能审批/执行的用户集合,具体的用户集合从ApprovalFormModel的approver_can字段同步'),
        ),
        migrations.AlterField(
            model_name='workformmodel',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, '重要且紧急'), (1, '不重要但紧急'), (2, '重要但不紧急'), (3, '不重要且不紧急')], verbose_name='紧急程度'),
        ),
    ]
