# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0019_auto_20180125_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalformmodel',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最终审批/执行人'),
        ),
        migrations.AlterField(
            model_name='workformmodel',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='申请人,与用户表多对一关联'),
        ),
    ]
