# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0020_auto_20180125_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalformmodel',
            name='result',
            field=models.CharField(choices=[('0', '审批/验证通过'), ('1', '拒绝审批/执行'), ('2', '暂停审批/执行'), ('3', '执行/验证异常')], max_length=10, null=True, verbose_name='审批/执行结果'),
        ),
    ]
