# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0021_auto_20180130_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workformtypemodel',
            name='cn_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='工单类型中文名称'),
        ),
        migrations.AlterField(
            model_name='workformtypemodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='工单类型名称'),
        ),
    ]
