# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0022_auto_20180218_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='workformmodel',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[('0', '项目需求'), ('1', '故障修复'), ('2', '技术优化'), ('3', '其他')], null=True, verbose_name='上线原因'),
        ),
    ]
