# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0024_auto_20180228_1628'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='approvalformmodel',
            index_together=set([('process', 'workform')]),
        ),
    ]
