# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0025_auto_20180319_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='workformmodel',
            name='database_name',
            field=models.CharField(default='no', max_length=200, verbose_name='数据库名称'),
        ),
    ]
