# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server_IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20, null=True, verbose_name='主机名')),
                ('ssh_port', models.CharField(default='22', max_length=5, verbose_name='SSH 端口号')),
                ('private_ip', models.CharField(max_length=15, unique=True, verbose_name='私网IP')),
                ('public_ip', models.CharField(max_length=15, null=True, verbose_name='公网IP')),
                ('env', models.CharField(max_length=10, verbose_name='所属环境:dev/test/online/ops')),
                ('server_brand', models.CharField(max_length=50, null=True, verbose_name='服务器品牌')),
                ('server_model', models.CharField(max_length=50, null=True, verbose_name='服务器型号')),
                ('os_version', models.CharField(max_length=50, null=True, verbose_name='系统版本')),
                ('cpu_type', models.CharField(max_length=50, null=True, verbose_name='CPU类型')),
                ('cpu_count', models.IntegerField(max_length=2, null=True, verbose_name='CPU核数')),
                ('mem', models.CharField(max_length=20, null=True, verbose_name='内存大小')),
                ('swap_size', models.CharField(max_length=10, null=True, verbose_name='SWAP 空间大小')),
                ('disk_size', models.CharField(max_length=50, null=True, verbose_name='物理磁盘大小')),
                ('part_mount', models.CharField(max_length=100, null=True, verbose_name='分区挂载情况')),
                ('idc', models.CharField(max_length=50, null=True, verbose_name='归属机房')),
                ('status', models.IntegerField(max_length=2, verbose_name='服务器状态:0-在线,1-下线')),
                ('online_time', models.DateTimeField(max_length=50, null=True, verbose_name='服务器上架时间')),
                ('offline_time', models.DateTimeField(max_length=50, null=True, verbose_name='服务器下架时间')),
            ],
            options={
                'ordering': ['private_ip'],
                'db_table': 'server_idc',
            },
        ),
    ]
