# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='应用名')),
                ('env', models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('online', '生产'), ('ops', '运维'), ('gray', '预发布')], default='online', max_length=10, verbose_name='所属环境')),
                ('describe', models.CharField(max_length=200, null=True, verbose_name='对应用的简单描述')),
                ('path', models.CharField(max_length=200, null=True, verbose_name='应用部署的路径')),
                ('script', models.CharField(max_length=200, null=True, verbose_name='应用启动脚本')),
                ('log', models.CharField(max_length=200, null=True, verbose_name='应用日志路径')),
                ('ports', models.CharField(max_length=200, null=True, verbose_name='应用打开的端口')),
                ('way', models.CharField(choices=[('0', 'tomcat'), ('1', 'jar'), ('3', 'node'), ('4', 'php'), ('5', '其他')], max_length=10, null=True, verbose_name='部署方式')),
                ('type', models.CharField(choices=[('0', '核心应用'), ('1', '一般应用'), ('2', '中间件'), ('3', '其他')], max_length=10, null=True, verbose_name='应用类型')),
                ('status', models.CharField(choices=[('0', '运行中'), ('1', '待上线'), ('2', '已停服')], max_length=10, null=True, verbose_name='应用状态')),
                ('online_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='应用上架时间')),
                ('offline_time', models.DateTimeField(null=True, verbose_name='应用下线时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='应用最后更新时间')),
            ],
            options={
                'db_table': 'cmdb',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CmdbStatisticByDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myday', models.DateField(unique=True, verbose_name='统计时间')),
                ('count', models.PositiveSmallIntegerField(verbose_name='应用数量')),
                ('compared_with_yesterday', models.CharField(default='0', max_length=5, verbose_name='与昨日相比变化的数量')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='应用最后更新时间')),
            ],
            options={
                'db_table': 'cmdb_statistic_by_day',
                'ordering': ['myday'],
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='IDC 简称')),
                ('cn_name', models.CharField(max_length=100, verbose_name='IDC 中文名')),
                ('address', models.CharField(max_length=100, verbose_name='IDC 地址')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='IDC 联系电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='IDC 邮箱')),
                ('user', models.CharField(max_length=32, null=True, verbose_name='IDC 联系人')),
                ('online_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='IDC添加时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最后一次更新时间')),
            ],
            options={
                'db_table': 'idc',
                'permissions': (('view_idc', '查看idc列表'),),
            },
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, null=True, verbose_name='主机名')),
                ('ssh_port', models.CharField(default='22', max_length=5, verbose_name='SSH 端口号')),
                ('private_ip', models.GenericIPAddressField(db_index=True, null=True, protocol='IPv4', unique=True, verbose_name='私网IP')),
                ('public_ip', models.GenericIPAddressField(null=True, protocol='IPv4', verbose_name='公网IP')),
                ('instance_id', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='实例ID,适用于云服务器')),
                ('instance_name', models.CharField(max_length=150, null=True, verbose_name='实例名称,适用于云服务器')),
                ('env', models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('online', '生产'), ('ops', '运维'), ('gray', '预发布')], default='online', max_length=10, verbose_name='所属环境')),
                ('server_brand', models.CharField(max_length=50, null=True, verbose_name='服务器品牌')),
                ('server_model', models.CharField(max_length=50, null=True, verbose_name='服务器型号,适用于 IDC 中服务器')),
                ('sn_code', models.CharField(max_length=20, null=True, unique=True, verbose_name='服务器SN号,适用于 IDC 中服务器')),
                ('cabinet_num', models.CharField(max_length=50, null=True, verbose_name='机柜编号,适用于 IDC 中服务器')),
                ('os_version', models.CharField(max_length=50, null=True, verbose_name='系统版本')),
                ('cpu_count', models.CharField(max_length=10, null=True, verbose_name='CPU核数')),
                ('mem', models.CharField(max_length=20, null=True, verbose_name='内存大小')),
                ('swap', models.CharField(max_length=10, null=True, verbose_name='SWAP 空间大小')),
                ('disk', models.CharField(max_length=200, null=True, verbose_name='物理磁盘大小')),
                ('disk_mount', models.CharField(max_length=100, null=True, verbose_name='分区挂载情况')),
                ('instance_type', models.CharField(max_length=50, null=True, verbose_name='实例规格,适用于云服务器')),
                ('charge_type', models.CharField(choices=[('PrePaid', '包年包月'), ('PostPaid', '按量付费')], max_length=10, null=True, verbose_name='付费类型,适用于云服务器')),
                ('renewal_type', models.CharField(choices=[('AutoRenewal', '自动续费'), ('Normal', '手动续费'), ('NotRenewal', '不在续费'), ('RenewalByUsed', '按量付费')], max_length=50, null=True, verbose_name='续费类型,适用于云服务器')),
                ('region', models.CharField(max_length=50, null=True, verbose_name='地域,适用于云服务器')),
                ('status', models.CharField(choices=[('Running', '运行中'), ('Starting', '启动中'), ('Stopping', '停止中'), ('Stopped', '已停止')], max_length=10, null=True, verbose_name='服务器状态')),
                ('monitor_status', models.CharField(choices=[('0', '正常'), ('1', '未监控')], max_length=10, null=True, verbose_name='服务器监控状态')),
                ('online_time', models.DateTimeField(null=True, verbose_name='服务器上架时间')),
                ('offline_time', models.DateTimeField(null=True, verbose_name='服务器下架时间')),
                ('expired_time', models.DateTimeField(null=True, verbose_name='服务器过期时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最后一次更新时间')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.IDC', verbose_name='归属机房')),
            ],
            options={
                'db_table': 'server',
                'ordering': ['private_ip'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatisticByDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myday', models.DateField(unique=True, verbose_name='统计时间')),
                ('count', models.PositiveSmallIntegerField(verbose_name='服务器数量')),
                ('compared_with_yesterday', models.CharField(default='0', max_length=5, verbose_name='与昨日相比变化的数量')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='应用最后更新时间')),
            ],
            options={
                'db_table': 'server_statistic_by_day',
                'ordering': ['myday'],
            },
        ),
        migrations.AddField(
            model_name='cmdbmodel',
            name='ips',
            field=models.ManyToManyField(to='resources.ServerModel', verbose_name='IP 地址'),
        ),
    ]
