# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_aliyun',
            old_name='disk_size',
            new_name='disk',
        ),
        migrations.RenameField(
            model_name='server_aliyun',
            old_name='part_mount',
            new_name='disk_mount',
        ),
        migrations.RenameField(
            model_name='server_aliyun',
            old_name='renewal_way',
            new_name='renewal_type',
        ),
        migrations.RenameField(
            model_name='server_aliyun',
            old_name='swap_size',
            new_name='swap',
        ),
        migrations.RenameField(
            model_name='server_idc',
            old_name='disk_size',
            new_name='disk',
        ),
        migrations.RenameField(
            model_name='server_idc',
            old_name='part_mount',
            new_name='disk_mount',
        ),
        migrations.RenameField(
            model_name='server_idc',
            old_name='swap_size',
            new_name='swap',
        ),
    ]
