# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdbmodel',
            name='ips',
        ),
        migrations.AddField(
            model_name='cmdbmodel',
            name='ips',
            field=models.ManyToManyField(to='resources.ServerAliyunModel', verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='cmdbmodel',
            name='status',
            field=models.CharField(choices=[('0', '运行中'), ('1', '已停服'), ('1', '待上线')], max_length=10, null=True, verbose_name='应用状态'),
        ),
    ]
