# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20171218_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbmodel',
            name='status',
            field=models.CharField(choices=[('0', '运行中'), ('1', '待上线'), ('2', '已停服')], max_length=10, null=True, verbose_name='应用状态'),
        ),
    ]
