# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_idc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'permissions': (('view_idc', '查看idc列表'),)},
        ),
    ]
