# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20171219_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbmodel',
            name='env',
            field=models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('online', '生产'), ('ops', '运维'), ('gray', '预发布')], default='online', max_length=10, verbose_name='所属环境'),
        ),
        migrations.AddField(
            model_name='cmdbmodel',
            name='way',
            field=models.CharField(choices=[('0', 'tomcat'), ('1', 'jar'), ('3', 'node'), ('4', 'php'), ('5', '其他')], max_length=10, null=True, verbose_name='部署方式'),
        ),
        migrations.AlterField(
            model_name='cmdbmodel',
            name='type',
            field=models.CharField(choices=[('0', '核心应用'), ('1', '一般应用'), ('2', '中间件'), ('3', '其他')], max_length=10, null=True, verbose_name='应用类型'),
        ),
        migrations.AlterField(
            model_name='serveraliyunmodel',
            name='env',
            field=models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('online', '生产'), ('ops', '运维'), ('gray', '预发布')], default='online', max_length=10, verbose_name='所属环境'),
        ),
    ]
