# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20171207_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_aliyun',
            name='online_time',
            field=models.DateTimeField(null=True, verbose_name='服务器上架时间'),
        ),
    ]
