# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20171019_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_idc',
            name='cabinet_num',
            field=models.CharField(max_length=20, null=True, verbose_name='机柜编号'),
        ),
        migrations.AddField(
            model_name='server_idc',
            name='last_update_time',
            field=models.DateTimeField(max_length=50, null=True, verbose_name='最后一次更新时间'),
        ),
        migrations.AddField(
            model_name='server_idc',
            name='sn_code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='服务器SN号'),
        ),
    ]
