# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20171220_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbStatisticByDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myday', models.DateField(unique=True, verbose_name='统计时间')),
                ('count', models.PositiveSmallIntegerField(verbose_name='应用数量')),
                ('compared_with_yesterday', models.CharField(default='0', max_length=5, verbose_name='与昨日相比变化的数量')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='应用最后更新时间')),
            ],
            options={
                'db_table': 'cmdb_statistic_by_day',
                'ordering': ['myday'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatisticByDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myday', models.DateField(verbose_name='统计时间')),
                ('count', models.PositiveSmallIntegerField(verbose_name='服务器数量')),
                ('compared_with_yesterday', models.CharField(default='0', max_length=5, verbose_name='与昨日相比变化的数量')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='应用最后更新时间')),
            ],
            options={
                'db_table': 'server_statistic_by_day',
                'ordering': ['myday'],
            },
        ),
    ]
