# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20180108_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdbstatisticbydaymodel',
            name='compared_with_yesterday',
        ),
        migrations.RemoveField(
            model_name='serverstatisticbydaymodel',
            name='compared_with_yesterday',
        ),
    ]
