# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20171210_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_aliyun',
            name='cpu_count',
            field=models.CharField(max_length=10, null=True, verbose_name='CPU核数'),
        ),
    ]
