# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_cmdbstatisticbydaymodel_serverstatisticbydaymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatisticbydaymodel',
            name='myday',
            field=models.DateField(unique=True, verbose_name='统计时间'),
        ),
    ]
