# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('resources', '0007_cmdbmodel_ansible_playbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbmodel',
            name='dev_team',
            field=models.ManyToManyField(to='auth.Group', verbose_name='负责的开发组'),
        ),
    ]
