# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20171210_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_aliyun',
            name='renewal_type',
            field=models.CharField(choices=[('AutoRenewal', '自动续费'), ('Normal', '手动续费'), ('NotRenewal', '不在续费'), ('RenewalByUsed', '按量付费')], max_length=50, null=True, verbose_name='续费类型'),
        ),
    ]
