# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20171212_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_aliyun',
            name='env',
            field=models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('online', '生产'), ('ops', '运维')], default='online', max_length=10, verbose_name='所属环境'),
        ),
    ]
