# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20171212_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_aliyun',
            name='disk',
            field=models.CharField(max_length=200, null=True, verbose_name='物理磁盘大小'),
        ),
    ]
