# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20171212_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_aliyun',
            name='hostname',
            field=models.CharField(max_length=50, null=True, verbose_name='主机名'),
        ),
    ]
