# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20171212_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_aliyun',
            name='idc',
        ),
    ]
