# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_remove_server_aliyun_idc'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后一次更新时间'),
        ),
        migrations.AddField(
            model_name='idc',
            name='online_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='IDC添加时间'),
        ),
    ]
