# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('operator', models.CharField(max_length=20, null=True, verbose_name='运营商')),
                ('provinces', models.CharField(max_length=20, null=True, verbose_name='所属省份')),
            ],
            options={
                'db_table': 'mobile',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='姓名')),
                ('sex', models.CharField(max_length=10, null=True, verbose_name='性别')),
                ('age', models.CharField(max_length=5, null=True, verbose_name='年龄')),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.AddField(
            model_name='mobile',
            name='people_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.People'),
        ),
    ]
