# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile',
            new_name='MobileTest',
        ),
    ]
