# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171101_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=20, null=True, verbose_name='工作岗位')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('technique', models.CharField(max_length=20, null=True, verbose_name='技术种类')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='persons',
            field=models.ManyToManyField(to='dashboard.Person'),
        ),
    ]
