# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171102_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='mobiletest',
            name='people_test',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='MobileTest',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
