# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='last_change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
