# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userextend_last_change_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextend',
            options={'verbose_name': '扩展用户表'},
        ),
        migrations.AddField(
            model_name='userextend',
            name='role',
            field=models.CharField(choices=[('0', 'leader'), ('1', 'member')], default='1', max_length=10, verbose_name='角色'),
        ),
    ]
