INSERT INTO `tts_config` VALUES (1, 'STOCK_FILE_LAST_MODIFIED_TIME', '');
INSERT INTO `tts_config` VALUES (2, 'STOCK_FILE_SUCCESS_SYNC_TIME', '');
INSERT INTO `tts_config` VALUES (3, 'SHOP_STOCK_FILE_LAST_MODIFIED_TIME', '');
INSERT INTO `tts_config` VALUES (4, 'SHOP_STOCK_FILE_SUCCESS_SYNC_TIME', '');
INSERT INTO `tts_config` VALUES (5, 'SHOP_STOCK_LAST_SEND_SYNC_MESSAGE_TIME', '');