# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_status', models.CharField(choices=[('success', '发布成功'), ('failure', '发布失败')], max_length=10, null=True, verbose_name='发布状态')),
                ('pub_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间')),
                ('ip', models.ManyToManyField(to='resources.ServerModel', verbose_name='模块的服务器IP地址')),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.CmdbModel', verbose_name='模块名')),
                ('pub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '发布历史表',
                'db_table': 'publish_history',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='publishversionmodel',
            name='ip',
        ),
        migrations.AlterField(
            model_name='publishversionmodel',
            name='status',
            field=models.CharField(choices=[('running', '当前运行的主版本'), ('run_pre', '之前运行过的版本'), ('rollback', '发生了回滚的版本'), ('packed', '已经打包且未发布的版本')], default='packed', max_length=10, verbose_name='版本状态'),
        ),
        migrations.AddField(
            model_name='publishhistorymodel',
            name='version_now',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.PublishVersionModel', verbose_name='当前发布的版本号'),
        ),
        migrations.AddField(
            model_name='publishhistorymodel',
            name='version_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publish.PublishVersionModel', verbose_name='上一次使用的版本号'),
        ),
    ]
