# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_publishhistorymodel_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishhistorymodel',
            name='pub_log_file',
            field=models.CharField(max_length=200, null=True, verbose_name='发布脚本执行日志'),
        ),
    ]
