# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_publishhistorymodel_pub_log_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishhistorymodel',
            name='version_pre',
        ),
    ]
