# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_remove_publishhistorymodel_version_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishhistorymodel',
            name='env',
            field=models.CharField(choices=[('online', '生产'), ('gray', '预发布')], max_length=10, null=True, verbose_name='环境'),
        ),
    ]
