# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_auto_20180321_1049'),
        ('publish', '0007_auto_20180321_1430'),
    ]

    operations = [
    ]
